version: "3.8"

services:
  postgres:
    image: postgres:latest
    container_name: imdb-db
    ports:
      - "5435:5432"
    environment:
      POSTGRES_DB: imdb-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
