openapi: "3.0.2"
info:
  title: iMDB API
  version: "1.0"
components:
  # securitySchemes:
  #   bearerAuth:
  #     type: http
  #     scheme: bearer
  #     bearerFormat: JWT
  #     description: Enter your bearer token in the format **bearer &lt;token>**
  parameters:
    offsetParam:
      in: query
      name: offset
      schema:
        type: integer
        default: 0
        minimum: 0
      required: false
      description: The number of items to skip before starting to collect the result set
    limitParam:
      in: query
      name: limit
      schema:
        type: integer
        default: 10
        minimum: 1
        maximum: 50
      required: false
      description: The maximum numbers of items to return per page
tags:
  - name: Movies
paths:
  /movies:
    get:
      tags:
        - Movies
      responses:
        "200":
          description: Search done with success
          content:
            application/json:
              schema:
                type: object
                example:
                  id: d139015f-3b1c-4d05-b303-73bcfdd91149
                  message: Listed with success
        "401":
          description: "Error: Unauthorized"
          content:
            application/json:
              schema:
                type: object
                example:
                  error: Unauthorized
        "404":
          description: "Error: Not Found"
          content:
            application/json:
              schema:
                type: object
                example:
                  error: Movie not found
